apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "intellirouter.fullname" . }}-config
  labels:
    {{- include "intellirouter.labels" . | nindent 4 }}
data:
  default.toml: |
    # Default configuration for IntelliRouter
    [server]
    host = "0.0.0.0"
    port = 8080

    [logging]
    level = "{{ .Values.config.logLevel }}"

    [redis]
    {{- if .Values.redis.enabled }}
    host = "{{ include "intellirouter.fullname" . }}-redis-master"
    port = 6379
    {{- else }}
    host = "localhost"
    port = 6379
    {{- end }}

    [chromadb]
    {{- if .Values.chromadb.enabled }}
    host = "{{ include "intellirouter.fullname" . }}-chromadb"
    port = {{ .Values.chromadb.service.port }}
    {{- else }}
    host = "localhost"
    port = 8001
    {{- end }}