{{- range .Values.roles }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "intellirouter.fullname" $ }}-{{ .name }}
  labels:
    {{- include "intellirouter.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .name }}
spec:
  {{- if not $.Values.autoscaling.enabled }}
  replicas: {{ .replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "intellirouter.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ .name }}
  template:
    metadata:
      {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "intellirouter.selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/component: {{ .name }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "intellirouter.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $.Chart.Name }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          env:
            - name: INTELLIROUTER_ENVIRONMENT
              value: {{ $.Values.config.environment }}
            - name: INTELLIROUTER__TELEMETRY__LOG_LEVEL
              value: {{ $.Values.config.logLevel }}
            - name: INTELLIROUTER__IPC__SECURITY__ENABLED
              value: {{ $.Values.config.ipcSecurityEnabled | quote }}
            - name: INTELLIROUTER__IPC__SECURITY__TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "intellirouter.fullname" $ }}-secret
                  key: ipc-token
            {{- range $key, $value := .config }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- if $.Values.redis.enabled }}
            - name: INTELLIROUTER__MEMORY__BACKEND_TYPE
              value: "redis"
            - name: INTELLIROUTER__MEMORY__REDIS_URL
              value: "redis://{{ include "intellirouter.fullname" $ }}-redis-master:6379"
            - name: INTELLIROUTER__MEMORY__REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "intellirouter.fullname" $ }}-redis
                  key: redis-password
            {{- end }}
          ports:
            {{- range .ports }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
              protocol: {{ .protocol }}
            {{- end }}
          {{- if .livenessProbe }}
          livenessProbe:
            {{- toYaml .livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .readinessProbe }}
          readinessProbe:
            {{- toYaml .readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- if .resources }}
            {{- toYaml .resources | nindent 12 }}
            {{- else }}
            {{- toYaml $.Values.resources | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /app/config
            {{- if .volumeMounts }}
            {{- toYaml .volumeMounts | nindent 12 }}
            {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "intellirouter.fullname" $ }}-config
        {{- if and (eq .name "router") $.Values.persistence.logs.enabled }}
        - name: logs
          persistentVolumeClaim:
            claimName: {{ include "intellirouter.fullname" $ }}-logs-{{ .name }}
        {{- end }}
        {{- if and (eq .name "orchestrator") $.Values.persistence.logs.enabled }}
        - name: logs
          persistentVolumeClaim:
            claimName: {{ include "intellirouter.fullname" $ }}-logs-{{ .name }}
        {{- end }}
        {{- if and (eq .name "rag-injector") $.Values.persistence.logs.enabled }}
        - name: logs
          persistentVolumeClaim:
            claimName: {{ include "intellirouter.fullname" $ }}-logs-{{ .name }}
        {{- end }}
        {{- if and (eq .name "rag-injector") $.Values.persistence.documents.enabled }}
        - name: documents
          persistentVolumeClaim:
            claimName: {{ include "intellirouter.fullname" $ }}-documents
        {{- end }}
        {{- if and (eq .name "summarizer") $.Values.persistence.logs.enabled }}
        - name: logs
          persistentVolumeClaim:
            claimName: {{ include "intellirouter.fullname" $ }}-logs-{{ .name }}
        {{- end }}
        {{- if and (eq .name "summarizer") $.Values.persistence.personas.enabled }}
        - name: personas
          persistentVolumeClaim:
            claimName: {{ include "intellirouter.fullname" $ }}-personas
        {{- end }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}