{{- range .Values.roles }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "intellirouter.fullname" $ }}-{{ .name }}
  labels:
    {{- include "intellirouter.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .name }}
spec:
  {{- if not $.Values.autoscaling.enabled }}
  replicas: {{ .replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "intellirouter.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ .name }}
  template:
    metadata:
      {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "intellirouter.selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/component: {{ .name }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "intellirouter.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $.Chart.Name }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          env:
            - name: INTELLIROUTER_ENVIRONMENT
              value: {{ $.Values.config.environment }}
            - name: INTELLIROUTER__TELEMETRY__LOG_LEVEL
              value: {{ $.Values.config.logLevel }}
            - name: INTELLIROUTER__SERVER__HOST
              value: "0.0.0.0"
            - name: INTELLIROUTER__SERVER__PORT
              value: "8080"
            {{- range $key, $value := .config }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- if $.Values.redis.enabled }}
            - name: INTELLIROUTER__MEMORY__BACKEND_TYPE
              value: "redis"
            - name: INTELLIROUTER__MEMORY__REDIS_URL
              value: "redis://{{ include "intellirouter.fullname" $ }}-redis-master:6379"
            - name: INTELLIROUTER__MEMORY__REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "intellirouter.fullname" $ }}-redis
                  key: redis-password
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /app/config
      volumes:
        - name: config
          configMap:
            name: {{ include "intellirouter.fullname" $ }}-config
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}