{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "intellirouter.fullname" . }}
  labels:
    {{- include "intellirouter.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "intellirouter.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- with .Values.networkPolicy.ingressRules }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  egress:
    # Allow DNS resolution
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
    # Allow Redis access
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: redis
      ports:
        - protocol: TCP
          port: 6379
    # Allow ChromaDB access
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: chromadb
      ports:
        - protocol: TCP
          port: 8000
    # Allow internal service communication
    - to:
        - podSelector:
            matchLabels:
              {{- include "intellirouter.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 8080
    # Allow external API access for LLM providers
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
      ports:
        - protocol: TCP
          port: 443
{{- end }}