{{- if .Values.ollama.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "intellirouter.fullname" . }}-ollama
  labels:
    {{- include "intellirouter.labels" . | nindent 4 }}
    app.kubernetes.io/component: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "intellirouter.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ollama
  template:
    metadata:
      labels:
        {{- include "intellirouter.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ollama
    spec:
      containers:
        - name: ollama
          image: "{{ .Values.ollama.image.repository }}:{{ .Values.ollama.image.tag }}"
          imagePullPolicy: {{ .Values.ollama.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 11434
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /root/.ollama
          resources:
            {{- toYaml .Values.ollama.resources | nindent 12 }}
          {{- if .Values.ollama.gpu.enabled }}
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
          {{- end }}
      volumes:
        - name: data
          {{- if .Values.ollama.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "intellirouter.fullname" . }}-ollama
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.ollama.gpu.enabled }}
      nodeSelector:
        accelerator: nvidia-gpu
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "intellirouter.fullname" . }}-ollama
  labels:
    {{- include "intellirouter.labels" . | nindent 4 }}
    app.kubernetes.io/component: ollama
spec:
  type: {{ .Values.ollama.service.type }}
  ports:
    - port: {{ .Values.ollama.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "intellirouter.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ollama
{{- if and .Values.ollama.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "intellirouter.fullname" . }}-ollama
  labels:
    {{- include "intellirouter.labels" . | nindent 4 }}
    app.kubernetes.io/component: ollama
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.ollama.persistence.storageClass }}
  storageClassName: {{ .Values.ollama.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.ollama.persistence.size }}
{{- end }}
{{- end }}