{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "intellirouter.fullname" . }}
  labels:
    {{- include "intellirouter.labels" . | nindent 4 }}
rules:
  {{- with .Values.rbac.rules }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "intellirouter.fullname" . }}
  labels:
    {{- include "intellirouter.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "intellirouter.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "intellirouter.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}