apiVersion: v1
kind: Secret
metadata:
  name: {{ include "intellirouter.fullname" . }}-secret
  labels:
    {{- include "intellirouter.labels" . | nindent 4 }}
type: Opaque
data:
  # Add your secrets here
  # example: {{ randAlphaNum 32 | b64enc | quote }}