apiVersion: v1
kind: Secret
metadata:
  name: {{ include "intellirouter.fullname" . }}-secret
  labels:
    {{- include "intellirouter.labels" . | nindent 4 }}
type: Opaque
data:
  # IPC security token for inter-service communication
  ipc-token: {{ .Values.config.ipcSecurityToken | default (randAlphaNum 32) | b64enc | quote }}
  
  # API Keys for LLM providers (these should be provided via values or external secrets)
  {{- if .Values.apiKeys }}
  {{- if .Values.apiKeys.openai }}
  openai-api-key: {{ .Values.apiKeys.openai | b64enc | quote }}
  {{- end }}
  {{- if .Values.apiKeys.anthropic }}
  anthropic-api-key: {{ .Values.apiKeys.anthropic | b64enc | quote }}
  {{- end }}
  {{- if .Values.apiKeys.google }}
  google-api-key: {{ .Values.apiKeys.google | b64enc | quote }}
  {{- end }}
  {{- if .Values.apiKeys.mistral }}
  mistral-api-key: {{ .Values.apiKeys.mistral | b64enc | quote }}
  {{- end }}
  {{- if .Values.apiKeys.xai }}
  xai-api-key: {{ .Values.apiKeys.xai | b64enc | quote }}
  {{- end }}
  {{- if .Values.apiKeys.azureOpenai }}
  azure-openai-api-key: {{ .Values.apiKeys.azureOpenai | b64enc | quote }}
  {{- end }}
  {{- end }}