# EKS specific values for intellirouter

service:
  type: ClusterIP

ingress:
  enabled: true
  className: "alb"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/healthcheck-path: /health
  hosts:
    - host: intellirouter.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: intellirouter-tls
      hosts:
        - intellirouter.example.com

resources:
  limits:
    cpu: 2000m
    memory: 2Gi
  requests:
    cpu: 1000m
    memory: 1Gi

# Use EBS for persistence
chromadb:
  persistence:
    enabled: true
    size: 10Gi

# Use node selectors for EKS
nodeSelector:
  eks.amazonaws.com/nodegroup: intellirouter

# Role-specific configuration with more replicas for production
roles:
  - name: router
    replicas: 2
    config:
      INTELLIROUTER_ROLE: router
  - name: orchestrator
    replicas: 2
    config:
      INTELLIROUTER_ROLE: orchestrator
  - name: model_registry
    replicas: 2
    config:
      INTELLIROUTER_ROLE: model_registry
  - name: chain_engine
    replicas: 2
    config:
      INTELLIROUTER_ROLE: chain_engine

# Enable autoscaling for production
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80