version: '3.8'

services:
  intellirouter:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
    environment:
      - RUST_BACKTRACE=1
      - INTELLIROUTER__TELEMETRY__LOG_LEVEL=debug
    command: [ "cargo", "watch", "-x", "run -- run --role all" ]

volumes:
  cargo-cache:
  target-cache:
