# Local configuration for IntelliRouter

# Server configuration
[server]
host = "0.0.0.0"
port = 8080

# Model registry configuration
[model_registry]
default_provider = "anthropic"

# Memory configuration - using in-memory backend to avoid database dependencies
[memory]
backend_type = "in_memory"

# Disable features that require external dependencies
[rag]
enabled = false

[plugin_sdk]
enabled = false

[auth]
auth_enabled = false